#park:
#    resource: "@ParkBundle/Resources/config/routing.yml"
#    prefix:   /

park:
    resource: "@ParkBundle/Controller"
    type: annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
